layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: docs/Machine_Learning.png
    
  # - name: Data Science
    # web_url: https://github.com/topics/data-science
    # image_url: docs/Data_Science.png
    
  - name: Stochastics
    web_url: https://github.com/topics/stochastic-processes
    image_url: docs/Stochastic_Simulation.png
    
  # - name: Rare Events
    # web_url: https://en.wikipedia.org/wiki/Rare_event_sampling
    # image_url: docs/Rare_Events.png
    
  - name: Optimization
    web_url: https://en.wikipedia.org/wiki/Mathematical_optimization
    image_url: docs/Optimization.png
    
projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: nathan.sanford.50
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: nathan-sanford-1b3476162
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  